### ISSUE TITLE
An Extra Paragraph with Japanese Settings

### ISSUE THREAD

**Issue by ch1h0kd** [virufy/study#119]
On the consent page, there is an extra paragraph with Japanese settings.
 

> "以下のチェックボックスにチェックを入れることで、参加者は、Virufyに対し、本同意書記載の目的のために、また、本同意書及び [Virufy Privacy Policy](https://www.google.com/url?q=https://virufy.org/en/privacy_policy/&sa=D&source=editors&ust=1677794208481489&usg=AOvVaw3bO4T_WWIqiwsyACrnqyjk)でより詳細に規定されている内容に従い、あなた の情報を取得、加工、共有することについて、明示的で、かつ自由な意思及び十分な情報に基づいた同意を行うことになります。
☐ - 私は、18歳以上です。
☐ - 私は、本同意書及び [Virufy Privacy Policy](https://www.google.com/url?q=https://virufy.org/en/privacy_policy/&sa=D&source=editors&ust=1677794208482681&usg=AOvVaw3IXeJmzjL6SegS9R7HVvNH)並びにこれらに基づく個人情報、生体認証情報及び健康情報の取得、加工及び第三者に対する共有について同意します。"

**Comment by mduthey** [comment]
Solved on #123
